"""
Created on Thu Jan 13 06:43:31 2022
"""

import matplotlib.pyplot as plt
import pandas as pd


def plot_lightcurve(df: pd.DataFrame, time_period: float, x_axis: str = 't/P', y_axis: str = 'Mbol') -> None:
    """
    Function to plot the light curve obtained from TwoStars program

    Parameters
    ----------
    df :
        dataframe, consisting of the parameters from TwoStars output csv file.
    time_period :
        The time period of the binary generated by TwoStars.
    x_axis :
        dataframe key to plot on x_axis, defaults to t/P.
    y_axis :
        dataframe key to plot on y_axis, defaults to Mbol
    
    Returns
    ----------
    None:
        Plots the light curve of the binary star system.
    """

    plt.plot(df[x_axis] * time_period, df[y_axis], 'k-.')
    plt.gca().invert_yaxis()
    plt.xlabel('Period [d]')
    plt.ylabel('Bolometric magnitude')
    plt.grid('on')
    plt.tight_layout()
